sources:
- type: imgur
  config: wallpapers
- type: imgur
  config: wallpaper
- type: subreddit
  config: wallpapers
- type: subreddit
  config: wallpaper
changePeriod: 10
failRetries: 10
failWait: 1
aspectRatioMargin: 0.3
