sources:
- type: imgur
  config: wallpapers
- type: imgur
  config: wallpaper
- type: subreddit
  config: wallpapers
- type: subreddit
  config: wallpaper
- type: earthview
  config: earthview
changePeriod: 10
failRetries: 10
failWait: 1
aspectRatioMargin: 0.3
minResolution:
- 1280
- 720
duplicateTimeout: 30
